### ISSUE TITLE
import statements

### ISSUE THREAD

**Issue by curlyfro** [bodiddlie/angular2-vs2015-example#1]
when you ctrl+click on your angular2 import modulenames does it link back and open that file for you?  mine doesn't and my imported symbols are red.  i have vs2015 update1, typescript 1.7.5, latest version of node.

do you have similar issues?

i noticed you have a typings folder with a missing 'tsd.d.ts' file.  i searched stackoverflow and saw where someone put this in their 'tsd.d.ts' file:
export \* from './../node_modules/angular2/core';
export \* from './../node_modules/angular2/common';
export \* from './../node_modules/angular2/http';
export \* from './../node_modules/angular2/router';
export \* from './../node_modules/angular2/platform/browser';

is this supposed to help with the symbols?  this didn't work for me.  do i need to reference it somehow?  i see your tsd.json file but how does all of this work within vs2015?

**Comment by bodiddlie** [comment]
Getting this all to work in vs2015 has been an adventure to say the least. I started this repo with the idea I would write up a tutorial post once I got it working. 

The tricky part is configuring the project for typescript. I have a typings folder, from when I started playing around, but in the current iteration, I don't actually have any installed typings. At some point recently, Angular2 switched to using the node style of modules and ditched their typings (if you install the latest via tsd, it's basically just a README saying to point to node_modules). 

VS2015 has support for tsconfig.json files, but only _really_ uses them in ASP.NET vNext projects. In anything else, the project file (.csproj in this case) overrides the tsconfig.json. So, in order to get the editor to work properly, you need to right click the project in the solution explorer, unload project, then right click and edit the project file and make the following changes:

Towards the bottom, find the `<PropertyGroup>` section that has a bunch of `<TypeScript*>` tags and add:

```
<TypeScriptExperimentalDecorators>True</TypeScriptExperimentalDecorators>
<TypeScriptModuleResolution>NodeJs</TypeScriptModuleResolution>
```

These are at line 200 in the [.csproj](https://github.com/bodiddlie/angular2-vs2015-example/blob/master/TypescriptNG2/TypescriptNG2.csproj) for this repo.

These were the first thing that I tried after a few hours of googling, and it got the editor to work, but I couldn't build the solution. The `NodeJs` entry above is what gets the editor to see the correct typings from the node_modules folder, but when it calls out the tsc compiler, it passes the actual flag `NodeJs` instead of `node`, which the compiler fails on. So, to fix this add the following in the .csproj as well, in the first `<PropertyGroup>` of the file:

```
<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
```

This will turn off compiling of typescript from withing VS. That means you'll need some kind of external build tool, which is better IMHO anyway. I'm using webpack for this one.

Hope this helps.

**Comment by curlyfro** [comment]
trying now...

**Comment by curlyfro** [comment]
hmmmm, i see your TypeScriptModuleResolution but i still can't get the editor to work :(  are there any other prerequisites to getting the editor to work?

**Comment by bodiddlie** [comment]
Are you trying on your own project, or did you pull this and are trying to get it to work? Just want to be clear on your situation.

**Comment by curlyfro** [comment]
both.  i saw your answer while i was working on my ng2 project.  that didn't work.  then i pulled down yours again and that didn't work either.

**Comment by bodiddlie** [comment]
Hmmmmm, I just went through and created a new project and got it working. One thing I noticed was that the `<PropertyGroup>` towards the bottom with all the `<TypeScript*>` options didn't show up until I went in to the project properties page and changed some settings and saved the project. Then I could add the experimental decorators and module resolution tags. Once those and the compile blocked tags were added, the editor recognizes and I can F12 on the imports to go straight to the definitions.

Not sure what the problem might be. Care to post your .csproj file?

**Comment by curlyfro** [comment]
i added a test project to [github](https://github.com/curlyfro/Ng2.).  please take a look.

**Comment by curlyfro** [comment]
[github](https://github.com/curlyfro/Ng2)

**Comment by bodiddlie** [comment]
Okay, I cloned your project and got it working locally. I sent a pull request with my changes.

**Comment by curlyfro** [comment]
i tried that... still no dice.  it must be something with my system.  at work now.  i'll try on my computer later.

thanks for your help.  i appreciate all that you've done.  i'll give you an update when i try from home.

**Comment by bodiddlie** [comment]
Hmmm. Sorry I couldn't help more right now. I'm at work too. I'll try pulling it down at home this afternoon and see if I can get it going there. I'm running VS2015 community there, so we'll see what a different environment gives us. Good luck.

**Comment by bodiddlie** [comment]
Just tried it at home and got the same result. Adding the TypeScriptCompilerBlock and TypeScriptModuleResolution settings got the editor to recognize the imports.
